version: '2'
services:
    nginx:
        image: nginx
        restart: always
        ports:
            - "3000:80"
            - "3001:443"
        volumes:
            - "./src:/var/www/html"
            - ".docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - ".docker/conf/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    php:
        build: .docker/build-php
        restart: always
        volumes:
            - "./src:/var/www/html"
            - ".docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ".docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_SERVICE_HOST=db
        command: php-fpm -F
    psql:
        image: postgres:10.1
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ".docker/conf/psql/:/docker-entrypoint-initdb.d/"
            - "./data/postgresql-data:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 3s
            timeout: 5s
            retries: 5
